name: nishishuozhezhong

on:
  workflow_dispatch:
  schedule:
    - cron: '47 4/6 * * *'
jobs:  # 22153
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nishishuozhezhong
        env:
          na2: ${{ secrets.na2 }}
        run: |
          echo $na2 | jq -r .pn21 | /bin/bash
          echo $wjkr4 | jq -r .p3 | /bin/bash
          echo $dzpo82245 | jq -r .qeg248 | /bin/bash

